name: Linter, Tests, Build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [master]

  pull_request:
    branches: [master]
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install modules
        run: npm install --force #удалить форс после миграции на 18реакт и рефакторинга
      - name: Prod build
        run: npm run build:prod
      - name: lint ts
        run: npm run lint:ts
        if: always()
      - name: lint css
        run: npm run lint:scss
        if: always()
      - name: Unit testing
        run: npm run test:unit
        if: always()

