name: Linter, Tests, Build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [master]

  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Install modules
        run: npm install

      - name: Prod build
        run: npm run build:prod

      - name: lint ts
        run: npm run lint:ts

      - name: lint css
        run: npm run lint:scss

      - name: Unit tests
        run: npm run test:unit
